// backend/features.js
const features = [
  { id: 'chat', title: 'Conversational Chat' },
  { id: 'image', title: 'Image Analyzer' },
  { id: 'document', title: 'Document Q&A' },
  { id: 'voice', title: 'Voice Message Understanding' },
  { id: 'livecall', title: 'Live AI Call' },
  { id: 'translate', title: 'Translator' },
  { id: 'summarize', title: 'Text Summarizer' },
  { id: 'code', title: 'Code Generator' },
  { id: 'debug', title: 'Code Debugger' },
  { id: 'math', title: 'Math Solver' },
  { id: 'email', title: 'Email Writer' },
  { id: 'story', title: 'Story Writer' },
  { id: 'recipe', title: 'Recipe Assistant' },
  { id: 'explain', title: 'Explain Like I\'m 5' },
  { id: 'compare', title: 'Comparison Tool' },
  { id: 'spell', title: 'Spelling & Grammar' },
  { id: 'mnemonics', title: 'Study Mnemonics' },
  { id: 'presentation', title: 'Slide Generator' },
  { id: 'resume', title: 'Resume Builder' },
  { id: 'interview', title: 'Interview Coach' },
  { id: 'sentiment', title: 'Sentiment Analysis' },
  { id: 'classify', title: 'Text Classifier' },
  { id: 'sql', title: 'SQL Assistant' },
  { id: 'excel', title: 'Excel Formula Helper' },
  { id: 'regex', title: 'Regex Helper' },
  { id: 'convert', title: 'Units Converter' },
  { id: 'calendar', title: 'Schedule Assistant' },
  { id: 'notes', title: 'Notes Organizer' },
  { id: 'todo', title: 'To-Do Manager' },
  { id: 'imageEdit', title: 'Image Editor' },
  { id: 'ocr', title: 'OCR from Image' },
  { id: 'pdf', title: 'PDF Q&A' },
  { id: 'audioTrans', title: 'Audio Transcription' },
  { id: 'voiceClone', title: 'Voice Clone (demo)' },
  { id: 'tts', title: 'Text To Speech' },
  { id: 'avatar', title: 'Avatar Generator' },
  { id: 'slideNotes', title: 'Slide Notes' },
  { id: 'lesson', title: 'Lesson Planner' },
  { id: 'homework', title: 'Homework Helper' },
  { id: 'shopping', title: 'Shopping Assistant' },
  { id: 'travel', title: 'Trip Planner' },
  { id: 'local', title: 'Local Info' },
  { id: 'health', title: 'Health Info (not medical advice)' },
  { id: 'finance', title: 'Finance Helper (info only)' },
  { id: 'imageSearch', title: 'Image Search' },
  { id: 'videoSummary', title: 'Video Summary' },
  { id: 'meetingNotes', title: 'Meeting Notes' },
  { id: 'mindmap', title: 'Mind Map Generator' },
  { id: 'game', title: 'Mini Game Maker' },
  { id: 'joke', title: 'Joke Generator' },
  { id: 'poetry', title: 'Poetry Maker' },
  { id: 'translateLive', title: 'Live Translation' },
  { id: 'safety', title: 'Content Safety Filter' },
  { id: 'creator', title: 'Creator Info' }
];

export default features;
