// Minimal metadata for 80 features. Frontend triggers POST /api/ai/:id
const features = [
  { id: 'chat', title: 'Conversational Chat', description: 'General chat assistant', defaultPrompt: 'Hello' },
  { id: 'summarize', title: 'Text Summarization', description: 'Summarize long text' },
  { id: 'translate', title: 'Translate Text', description: 'Translate between languages' },
  { id: 'paraphrase', title: 'Paraphrase', description: 'Rewrite text' },
  { id: 'grammar', title: 'Grammar Correction', description: 'Fix grammar' },
  { id: 'rewrite-tone', title: 'Rewrite Tone', description: 'Change tone' },
  { id: 'qa', title: 'Question Answering', description: 'Answer questions' },
  { id: 'codegen', title: 'Code Generation', description: 'Generate code' },
  { id: 'explain-code', title: 'Explain Code', description: 'Explain code snippets' },
  { id: 'fix-bug', title: 'Find & Fix Bug', description: 'Suggest code fixes' },
  { id: 'unit-tests', title: 'Unit Test Generator', description: 'Generate unit tests' },
  { id: 'sql-gen', title: 'SQL Generator', description: 'Generate SQL queries' },
  { id: 'data-clean', title: 'Data Cleaning', description: 'Suggest cleaning steps' },
  { id: 'excel-formula', title: 'Excel Formula Helper', description: 'Create formulas' },
  { id: 'image-gen', title: 'Image Generation', description: 'Generate images from prompts' },
  { id: 'image-edit', title: 'Image Edit (placeholder)', description: 'Edit image' },
  { id: 'text-to-speech', title: 'Text to Speech', description: 'Generate speech audio' },
  { id: 'speech-to-text', title: 'Speech to Text', description: 'Transcribe audio' },
  { id: 'summarize-audio', title: 'Summarize Audio', description: 'Summarize transcripts' },
  { id: 'meeting-notes', title: 'Meeting Notes', description: 'Generate meeting notes' },
  { id: 'conversation-insights', title: 'Conversation Insights', description: 'Extract insights' },
  { id: 'sentiment', title: 'Sentiment Analysis', description: 'Detect sentiment' },
  { id: 'entity-extraction', title: 'Entity Extraction', description: 'Extract named entities' },
  { id: 'keyword-extract', title: 'Keyword Extraction', description: 'Extract keywords' },
  { id: 'email-draft', title: 'Email Draft', description: 'Write professional email' },
  { id: 'cover-letter', title: 'Cover Letter', description: 'Generate cover letter' },
  { id: 'resume-review', title: 'Resume Review', description: 'Give resume feedback' },
  { id: 'job-descriptions', title: 'Job Description', description: 'Write job description' },
  { id: 'idea-brainstorm', title: 'Idea Brainstorm', description: 'Generate ideas' },
  { id: 'marketing-copy', title: 'Marketing Copy', description: 'Write ad copy' },
  { id: 'seo-optimizer', title: 'SEO Optimizer', description: 'Improve SEO' },
  { id: 'product-namer', title: 'Product Namer', description: 'Suggest product names' },
  { id: 'ux-review', title: 'UX Review', description: 'Review UI/UX' },
  { id: 'a-b-test', title: 'A/B Test Ideas', description: 'Generate A/B variants' },
  { id: 'legal-summarize', title: 'Legal Summarizer', description: 'Summarize legal docs' },
  { id: 'privacy-review', title: 'Privacy Advice', description: 'Suggest privacy best practices' },
  { id: 'cyber-ops', title: 'Cybersecurity Tips', description: 'Basic security recommendations' },
  { id: 'design-system', title: 'Design Tokens', description: 'Generate design tokens' },
  { id: 'tone-analyzer', title: 'Tone Analyzer', description: 'Detect tone' },
  { id: 'persona-gen', title: 'User Persona Generator', description: 'Create personas' },
  { id: 'roadmap-gen', title: 'Product Roadmap', description: 'Generate roadmap' },
  { id: 'feature-prioritize', title: 'Feature Prioritization', description: 'RICE scoring helper' },
  { id: 'bug-report', title: 'Bug Report Generator', description: 'Format bug reports' },
  { id: 'changelog', title: 'Changelog Writer', description: 'Write release notes' },
  { id: 'scheduler', title: 'Meeting Scheduler', description: 'Suggest meeting times' },
  { id: 'summary-action', title: 'Action Items', description: 'Extract action items' },
  { id: 'visualize-data', title: 'Data Visualization Plan', description: 'Suggest visualizations' },
  { id: 'regex-gen', title: 'Regex Generator', description: 'Create regex patterns' },
  { id: 'explain-ml', title: 'Explain ML Concepts', description: 'Explain ML simply' },
  { id: 'prompt-engineer', title: 'Prompt Engineering', description: 'Optimize prompts' },
  { id: 'persona-chat', title: 'Role-play Chat', description: 'Chat as a persona' },
  { id: 'story-gen', title: 'Story Generator', description: 'Write stories' },
  { id: 'poetry', title: 'Poetry Generator', description: 'Write poems' },
  { id: 'lesson-plan', title: 'Lesson Plan', description: 'Generate lesson plans' },
  { id: 'flashcards', title: 'Flashcards Creator', description: 'Create study flashcards' },
  { id: 'math-solver', title: 'Math Solver', description: 'Solve math problems step-by-step' },
  { id: 'chem-helper', title: 'Chemistry Helper', description: 'Explain reactions' },
  { id: 'medical-info', title: 'Medical Info (disclaimer)', description: 'Non-diagnostic medical info' },
  { id: 'fitness-plan', title: 'Fitness Plan', description: 'Create workout plans' },
  { id: 'meal-plan', title: 'Meal Planner', description: 'Create meal plans' },
  { id: 'budgeting', title: 'Budget Planner', description: 'Create budget' },
  { id: 'tax-tips', title: 'Tax Tips', description: 'Tax filing checklist' },
  { id: 'trivia', title: 'Trivia Generator', description: 'Create trivia questions' },
  { id: 'quiz-maker', title: 'Quiz Maker', description: 'Generate quizzes' },
  { id: 'game-idea', title: 'Game Idea', description: 'Suggest game concepts' },
  { id: 'music-lyrics', title: 'Music Lyrics', description: 'Write song lyrics' },
  { id: 'chord-prog', title: 'Chord Progression', description: 'Suggest chords' },
  { id: 'photo-caption', title: 'Photo Caption', description: 'Write captions' },
  { id: 'resume-tailor', title: 'Resume Tailor', description: 'Tailor resume to job' },
  { id: 'interview-prep', title: 'Interview Prep', description: 'Mock interview questions' },
  { id: 'cold-email', title: 'Cold Email', description: 'Write outreach emails' },
  { id: 'sales-pitch', title: 'Sales Pitch', description: 'Create sales pitch' },
  { id: 'invest-summary', title: 'Investment Summary', description: 'Summarize investment memo' },
  { id: 'risk-assess', title: 'Risk Assessment', description: 'Highlight key risks' },
  { id: 'compliance-check', title: 'Compliance Check', description: 'Basic compliance checklist' },
  { id: 'translation-multiple', title: 'Multi-language Translator', description: 'Translate into many languages' },
  { id: 'voice-persona', title: 'Voice Persona', description: 'Generate voice descriptions' }
];

export default features;
