const features = [
  { id: 'chat', title: 'Conversational Chat', defaultPrompt: 'Hello, tell me about yourself.' },
  { id: 'summarize', title: 'Text Summarization', defaultPrompt: 'Summarize this text:' },
  { id: 'translate', title: 'Translate Text', defaultPrompt: 'Translate the following to English:' },
  { id: 'paraphrase', title: 'Paraphrase', defaultPrompt: 'Paraphrase this sentence:' },
  { id: 'grammar', title: 'Grammar Correction', defaultPrompt: 'Correct grammar for:' },
  { id: 'rewrite-tone', title: 'Rewrite Tone', defaultPrompt: 'Rewrite this to sound more formal:' },
  { id: 'qa', title: 'Question Answering', defaultPrompt: 'Answer the question:' },
  { id: 'codegen', title: 'Code Generation', defaultPrompt: 'Write code to:' },
  { id: 'explain-code', title: 'Explain Code', defaultPrompt: 'Explain this code:' },
  { id: 'fix-bug', title: 'Find & Fix Bug', defaultPrompt: 'Find bugs and suggest fixes for the code:' },
  { id: 'unit-tests', title: 'Unit Test Generator', defaultPrompt: 'Generate unit tests for this function:' },
  { id: 'sql-gen', title: 'SQL Generator', defaultPrompt: 'Produce an SQL query to:' },
  { id: 'data-clean', title: 'Data Cleaning', defaultPrompt: 'How to clean dataset with columns: ...' },
  { id: 'excel-formula', title: 'Excel Formula Helper', defaultPrompt: 'Create an Excel formula to:' },
  { id: 'image-gen', title: 'Image Generation', defaultPrompt: 'Create a prompt to generate an image of:' },
  { id: 'image-edit', title: 'Image Edit', defaultPrompt: 'How to edit an image to:' },
  { id: 'text-to-speech', title: 'Text to Speech', defaultPrompt: 'Convert this text to SSML:' },
  { id: 'speech-to-text', title: 'Speech to Text', defaultPrompt: 'Transcribe the following audio (describe audio content):' },
  { id: 'summarize-audio', title: 'Summarize Audio', defaultPrompt: 'Summarize the transcript:' },
  { id: 'meeting-notes', title: 'Meeting Notes', defaultPrompt: 'Create meeting notes from the following:' },
  { id: 'conversation-insights', title: 'Conversation Insights', defaultPrompt: 'Extract insights from the conversation:' },
  { id: 'sentiment', title: 'Sentiment Analysis', defaultPrompt: 'Analyze sentiment for:' },
  { id: 'entity-extraction', title: 'Entity Extraction', defaultPrompt: 'Extract entities from:' },
  { id: 'keyword-extract', title: 'Keyword Extraction', defaultPrompt: 'Extract keywords from:' },
  { id: 'email-draft', title: 'Email Draft', defaultPrompt: 'Write an email to a hiring manager applying for:' },
  { id: 'cover-letter', title: 'Cover Letter', defaultPrompt: 'Write a cover letter for the role:' },
  { id: 'resume-review', title: 'Resume Review', defaultPrompt: 'Review this resume and give suggestions:' },
  { id: 'job-descriptions', title: 'Job Description', defaultPrompt: 'Create a job description for a:' },
  { id: 'idea-brainstorm', title: 'Idea Brainstorm', defaultPrompt: 'Brainstorm ideas for:' },
  { id: 'marketing-copy', title: 'Marketing Copy', defaultPrompt: 'Write short ad copy for:' },
  { id: 'seo-optimizer', title: 'SEO Optimizer', defaultPrompt: 'Optimize this content for SEO:' },
  { id: 'product-namer', title: 'Product Namer', defaultPrompt: 'Generate product names for:' },
  { id: 'ux-review', title: 'UX Review', defaultPrompt: 'Review this UI/UX and suggest improvements:' },
  { id: 'a-b-test', title: 'A/B Test Ideas', defaultPrompt: 'Suggest A/B test ideas for:' },
  { id: 'legal-summarize', title: 'Legal Summarizer', defaultPrompt: 'Summarize this legal document:' },
  { id: 'privacy-review', title: 'Privacy Advice', defaultPrompt: 'Suggest privacy best practices for an app that:' },
  { id: 'cyber-ops', title: 'Cybersecurity Tips', defaultPrompt: 'Security checklist for a web app:' },
  { id: 'design-system', title: 'Design Tokens', defaultPrompt: 'Create a basic design token set for a product:' },
  { id: 'tone-analyzer', title: 'Tone Analyzer', defaultPrompt: 'Analyze tone for the text:' },
  { id: 'persona-gen', title: 'User Persona Generator', defaultPrompt: 'Create a user persona for a product used by:' },
  { id: 'roadmap-gen', title: 'Product Roadmap', defaultPrompt: 'Generate a 6-month roadmap for:' },
  { id: 'feature-prioritize', title: 'Feature Prioritization', defaultPrompt: 'Prioritize these features using RICE:' },
  { id: 'bug-report', title: 'Bug Report Generator', defaultPrompt: 'Create a bug report for the issue:' },
  { id: 'changelog', title: 'Changelog Writer', defaultPrompt: 'Write release notes for these changes:' },
  { id: 'scheduler', title: 'Meeting Scheduler', defaultPrompt: 'Suggest meeting times for participants in:' },
  { id: 'summary-action', title: 'Action Items', defaultPrompt: 'Extract action items from the meeting transcript:' },
  { id: 'visualize-data', title: 'Visualize Data', defaultPrompt: 'Suggest visualizations for dataset with columns:' },
  { id: 'regex-gen', title: 'Regex Generator', defaultPrompt: 'Create a regex to match:' },
  { id: 'explain-ml', title: 'Explain ML Concepts', defaultPrompt: 'Explain the concept of:' },
  { id: 'prompt-engineer', title: 'Prompt Engineering', defaultPrompt: 'Improve this prompt:' },
  { id: 'persona-chat', title: 'Role-play Chat', defaultPrompt: 'Act as a friendly travel agent who:' },
  { id: 'story-gen', title: 'Story Generator', defaultPrompt: 'Write a short story about:' },
  { id: 'poetry', title: 'Poetry Generator', defaultPrompt: 'Write a short poem about:' },
  { id: 'lesson-plan', title: 'Lesson Plan', defaultPrompt: 'Create a lesson plan for teaching:' },
  { id: 'flashcards', title: 'Flashcards Creator', defaultPrompt: 'Create flashcards for the topic:' },
  { id: 'math-solver', title: 'Math Solver', defaultPrompt: 'Solve this math problem step-by-step:' },
  { id: 'chem-helper', title: 'Chemistry Helper', defaultPrompt: 'Explain the reaction:' },
  { id: 'medical-info', title: 'Medical Info', defaultPrompt: 'Explain symptoms and possible causes for:' },
  { id: 'fitness-plan', title: 'Fitness Plan', defaultPrompt: 'Create a 4-week fitness plan for someone who:' },
  { id: 'meal-plan', title: 'Meal Planner', defaultPrompt: 'Create a 7-day meal plan for:' },
  { id: 'budgeting', title: 'Budget Planner', defaultPrompt: 'Create a monthly budget for income and expenses:' },
  { id: 'tax-tips', title: 'Tax Tips', defaultPrompt: 'General tax tips for a freelancer in:' },
  { id: 'trivia', title: 'Trivia Generator', defaultPrompt: 'Create 5 trivia questions about world capitals' },
  { id: 'quiz-maker', title: 'Quiz Maker', defaultPrompt: 'Create a 10-question multiple-choice quiz on:' },
  { id: 'game-idea', title: 'Game Idea', defaultPrompt: 'Suggest indie game concepts for mobile devices:' },
  { id: 'music-lyrics', title: 'Music Lyrics', defaultPrompt: 'Write a chorus for a pop song about:' },
  { id: 'chord-prog', title: 'Chord Progression', defaultPrompt: 'Suggest a chord progression for a melancholic song in C major' },
  { id: 'photo-caption', title: 'Photo Caption', defaultPrompt: 'Write a caption for a photo of:' },
  { id: 'resume-tailor', title: 'Resume Tailor', defaultPrompt: 'Tailor this resume for the job posting:' },
  { id: 'interview-prep', title: 'Interview Prep', defaultPrompt: 'Generate common interview questions for a software engineer role' },
  { id: 'cold-email', title: 'Cold Email', defaultPrompt: 'Write a cold email to a potential client about:' },
  { id: 'sales-pitch', title: 'Sales Pitch', defaultPrompt: 'Create a short sales pitch for:' },
  { id: 'invest-summary', title: 'Investment Summary', defaultPrompt: 'Summarize this investment memo into key points:' },
  { id: 'risk-assess', title: 'Risk Assessment', defaultPrompt: 'Assess risks for the project:' },
  { id: 'compliance-check', title: 'Compliance Check', defaultPrompt: 'Compliance checklist for a SaaS handling user data:' },
  { id: 'translation-multiple', title: 'Multi-language Translator', defaultPrompt: 'Translate this into Spanish, French, and German:' },
  { id: 'voice-persona', title: 'Voice Persona', defaultPrompt: 'Create a voice persona for a calm, trustworthy narrator' }
];
export default features;
