const features = [
  { id: "chat", title: "General Chat", defaultPrompt: "Hello, tell me about yourself." },
  { id: "image-qa", title: "Ask about an uploaded image", defaultPrompt: "Ask a question about the uploaded image" },
  { id: "doc-qa", title: "Ask about a document", defaultPrompt: "Ask about the uploaded document" },
  { id: "voice-qa", title: "Ask after voice recording", defaultPrompt: "Ask a question based on the audio" },
  // Add more features here...
];

export default features;
// client/src/features/aiFeatureTemplates.js
const features = [
  // (existing 80 features — keep them if already present)
  { id: 'chat', title: 'Conversational Chat', defaultPrompt: 'Hello, tell me about yourself.' },
  { id: 'summarize', title: 'Text Summarization', defaultPrompt: 'Summarize this text:' },
  { id: 'translate', title: 'Translate Text', defaultPrompt: 'Translate the following to English:' },
  { id: 'paraphrase', title: 'Paraphrase', defaultPrompt: 'Paraphrase this sentence:' },
  { id: 'grammar', title: 'Grammar Correction', defaultPrompt: 'Correct grammar for:' },
  { id: 'rewrite-tone', title: 'Rewrite Tone', defaultPrompt: 'Rewrite this to sound more formal:' },
  { id: 'qa', title: 'Question Answering', defaultPrompt: 'Answer the question:' },
  { id: 'codegen', title: 'Code Generation', defaultPrompt: 'Write code to:' },
  { id: 'explain-code', title: 'Explain Code', defaultPrompt: 'Explain this code:' },
  { id: 'fix-bug', title: 'Find & Fix Bug', defaultPrompt: 'Find bugs and suggest fixes for the code:' },
  { id: 'unit-tests', title: 'Unit Test Generator', defaultPrompt: 'Generate unit tests for this function:' },
  { id: 'sql-gen', title: 'SQL Generator', defaultPrompt: 'Produce an SQL query to:' },
  { id: 'data-clean', title: 'Data Cleaning', defaultPrompt: 'How to clean dataset with columns: ...' },
  { id: 'excel-formula', title: 'Excel Formula Helper', defaultPrompt: 'Create an Excel formula to:' },
  { id: 'image-gen', title: 'Image Generation', defaultPrompt: 'Create a prompt to generate an image of:' },
  { id: 'image-edit', title: 'Image Edit', defaultPrompt: 'How to edit an image to:' },
  { id: 'text-to-speech', title: 'Text to Speech', defaultPrompt: 'Convert this text to SSML:' },
  { id: 'speech-to-text', title: 'Speech to Text', defaultPrompt: 'Transcribe the following audio (describe audio content):' },
  { id: 'summarize-audio', title: 'Summarize Audio', defaultPrompt: 'Summarize the transcript:' },
  { id: 'meeting-notes', title: 'Meeting Notes', defaultPrompt: 'Create meeting notes from the following:' },
  { id: 'conversation-insights', title: 'Conversation Insights', defaultPrompt: 'Extract insights from the conversation:' },
  { id: 'sentiment', title: 'Sentiment Analysis', defaultPrompt: 'Analyze sentiment for:' },
  { id: 'entity-extraction', title: 'Entity Extraction', defaultPrompt: 'Extract entities from:' },
  { id: 'keyword-extract', title: 'Keyword Extraction', defaultPrompt: 'Extract keywords from:' },
  { id: 'email-draft', title: 'Email Draft', defaultPrompt: 'Write an email to a hiring manager applying for:' },
  { id: 'cover-letter', title: 'Cover Letter', defaultPrompt: 'Write a cover letter for the role:' },
  { id: 'resume-review', title: 'Resume Review', defaultPrompt: 'Review this resume and give suggestions:' },
  { id: 'job-descriptions', title: 'Job Description', defaultPrompt: 'Create a job description for a:' },
  { id: 'idea-brainstorm', title: 'Idea Brainstorm', defaultPrompt: 'Brainstorm ideas for:' },
  { id: 'marketing-copy', title: 'Marketing Copy', defaultPrompt: 'Write short ad copy for:' },
  { id: 'seo-optimizer', title: 'SEO Optimizer', defaultPrompt: 'Optimize this content for SEO:' },
  { id: 'product-namer', title: 'Product Namer', defaultPrompt: 'Generate product names for:' },
  { id: 'ux-review', title: 'UX Review', defaultPrompt: 'Review this UI/UX and suggest improvements:' },
  { id: 'a-b-test', title: 'A/B Test Ideas', defaultPrompt: 'Suggest A/B test ideas for:' },
  { id: 'legal-summarize', title: 'Legal Summarizer', defaultPrompt: 'Summarize this legal document:' },
  { id: 'privacy-review', title: 'Privacy Advice', defaultPrompt: 'Suggest privacy best practices for an app that:' },
  { id: 'cyber-ops', title: 'Cybersecurity Tips', defaultPrompt: 'Security checklist for a web app:' },
  { id: 'design-system', title: 'Design Tokens', defaultPrompt: 'Create a basic design token set for a product:' },
  { id: 'tone-analyzer', title: 'Tone Analyzer', defaultPrompt: 'Analyze tone for the text:' },
  { id: 'persona-gen', title: 'User Persona Generator', defaultPrompt: 'Create a user persona for a product used by:' },
  { id: 'roadmap-gen', title: 'Product Roadmap', defaultPrompt: 'Generate a 6-month roadmap for:' },
  { id: 'feature-prioritize', title: 'Feature Prioritization', defaultPrompt: 'Prioritize these features using RICE:' },
  { id: 'bug-report', title: 'Bug Report Generator', defaultPrompt: 'Create a bug report for the issue:' },
  { id: 'changelog', title: 'Changelog Writer', defaultPrompt: 'Write release notes for these changes:' },
  { id: 'scheduler', title: 'Meeting Scheduler', defaultPrompt: 'Suggest meeting times for participants in:' },
  { id: 'summary-action', title: 'Action Items', defaultPrompt: 'Extract action items from the meeting transcript:' },
  { id: 'visualize-data', title: 'Data Visualization Plan', defaultPrompt: 'Suggest visualizations for dataset with columns:' },
  { id: 'regex-gen', title: 'Regex Generator', defaultPrompt: 'Create a regex to match:' },
  { id: 'explain-ml', title: 'Explain ML Concepts', defaultPrompt: 'Explain the concept of:' },
  { id: 'prompt-engineer', title: 'Prompt Engineering', defaultPrompt: 'Improve this prompt:' },
  { id: 'persona-chat', title: 'Role-play Chat', defaultPrompt: 'Act as a friendly travel agent who:' },
  { id: 'story-gen', title: 'Story Generator', defaultPrompt: 'Write a short story about:' },
  { id: 'poetry', title: 'Poetry Generator', defaultPrompt: 'Write a short poem about:' },
  { id: 'lesson-plan', title: 'Lesson Plan', defaultPrompt: 'Create a lesson plan for teaching:' },
  { id: 'flashcards', title: 'Flashcards Creator', defaultPrompt: 'Create flashcards for the topic:' },
  { id: 'math-solver', title: 'Math Solver', defaultPrompt: 'Solve this math problem step-by-step:' },
  { id: 'chem-helper', title: 'Chemistry Helper', defaultPrompt: 'Explain the reaction:' },
  { id: 'medical-info', title: 'Medical Info', defaultPrompt: 'Explain symptoms and possible causes for:' },
  { id: 'fitness-plan', title: 'Fitness Plan', defaultPrompt: 'Create a 4-week fitness plan for someone who:' },
  { id: 'meal-plan', title: 'Meal Planner', defaultPrompt: 'Create a 7-day meal plan for:' },
  { id: 'budgeting', title: 'Budget Planner', defaultPrompt: 'Create a monthly budget for income and expenses:' },
  { id: 'tax-tips', title: 'Tax Tips', defaultPrompt: 'General tax tips for a freelancer in:' },
  { id: 'trivia', title: 'Trivia Generator', defaultPrompt: 'Create 5 trivia questions about world capitals' },
  { id: 'quiz-maker', title: 'Quiz Maker', defaultPrompt: 'Create a 10-question multiple-choice quiz on:' },
  { id: 'game-idea', title: 'Game Idea', defaultPrompt: 'Suggest indie game concepts for mobile devices:' },
  { id: 'music-lyrics', title: 'Music Lyrics', defaultPrompt: 'Write a chorus for a pop song about:' },
  { id: 'chord-prog', title: 'Chord Progression', defaultPrompt: 'Suggest a chord progression for a melancholic song in C major' },
  { id: 'photo-caption', title: 'Photo Caption', defaultPrompt: 'Write a caption for a photo of:' },
  { id: 'resume-tailor', title: 'Resume Tailor', defaultPrompt: 'Tailor this resume for the job posting:' },
  { id: 'interview-prep', title: 'Interview Prep', defaultPrompt: 'Generate common interview questions for a software engineer role' },
  { id: 'cold-email', title: 'Cold Email', defaultPrompt: 'Write a cold email to a potential client about:' },
  { id: 'sales-pitch', title: 'Sales Pitch', defaultPrompt: 'Create a short sales pitch for:' },
  { id: 'invest-summary', title: 'Investment Summary', defaultPrompt: 'Summarize this investment memo into key points:' },
  { id: 'risk-assess', title: 'Risk Assessment', defaultPrompt: 'Assess risks for the project:' },
  { id: 'compliance-check', title: 'Compliance Check', defaultPrompt: 'Compliance checklist for a SaaS handling user data:' },
  { id: 'translation-multiple', title: 'Multi-language Translator', defaultPrompt: 'Translate this into Spanish, French, and German:' },
  { id: 'voice-persona', title: 'Voice Persona', defaultPrompt: 'Create a voice persona for a calm, trustworthy narrator' },

  // ---- 60 EXTRA FEATURE PLACEHOLDERS ----
  { id: 'extra-1', title: 'AI Brainstorm Hub', defaultPrompt: 'Brainstorm unique ideas for:' },
  { id: 'extra-2', title: 'Press Release Writer', defaultPrompt: 'Write a press release announcing:' },
  { id: 'extra-3', title: 'Product One-Pager', defaultPrompt: 'Create a one-pager for product:' },
  { id: 'extra-4', title: 'User Onboarding Flow', defaultPrompt: 'Design onboarding steps for:' },
  { id: 'extra-5', title: 'Customer Persona Segments', defaultPrompt: 'Create customer segments for:' },
  { id: 'extra-6', title: 'Social Post Calendar', defaultPrompt: 'Generate a 7-day social post calendar for:' },
  { id: 'extra-7', title: 'Microcopy Writer', defaultPrompt: 'Write microcopy for button: “' },
  { id: 'extra-8', title: 'FAQ Generator', defaultPrompt: 'Create FAQs for product:' },
  { id: 'extra-9', title: 'Churn Reduction Tips', defaultPrompt: 'Suggest ways to reduce churn for:' },
  { id: 'extra-10', title: 'Customer Support Reply', defaultPrompt: 'Write a polite support reply for issue:' },
  { id: 'extra-11', title: 'Localization Helper', defaultPrompt: 'Localize this text for:' },
  { id: 'extra-12', title: 'Brand Voice Guide', defaultPrompt: 'Create a short voice guide for brand:' },
  { id: 'extra-13', title: 'Slogan Creator', defaultPrompt: 'Create a catchy slogan for:' },
  { id: 'extra-14', title: 'Investor Pitch Bullets', defaultPrompt: 'Write 6 bullet points for investor pitch:' },
  { id: 'extra-15', title: 'Feature Explainer Video Script', defaultPrompt: 'Write a short video script for feature:' },
  { id: 'extra-16', title: 'Competitor Comparison', defaultPrompt: 'Compare product to competitor:' },
  { id: 'extra-17', title: 'Release Checklist', defaultPrompt: 'Create a release checklist for version:' },
  { id: 'extra-18', title: 'Meeting Agenda Generator', defaultPrompt: 'Make an agenda for meeting about:' },
  { id: 'extra-19', title: 'OKR Suggestions', defaultPrompt: 'Generate OKRs for team:' },
  { id: 'extra-20', title: 'Sprint Planner', defaultPrompt: 'Plan a 2-week sprint for:' },
  { id: 'extra-21', title: 'Customer Survey Creator', defaultPrompt: 'Create a short survey to measure satisfaction for:' },
  { id: 'extra-22', title: 'Ad Headline Tester', defaultPrompt: 'Generate 10 ad headlines for:' },
  { id: 'extra-23', title: 'Press Pitch Email', defaultPrompt: 'Write a pitch email to press about:' },
  { id: 'extra-24', title: 'Video Caption Writer', defaultPrompt: 'Write captions for social video about:' },
  { id: 'extra-25', title: 'Data Insights Summary', defaultPrompt: 'Summarize insights from dataset:' },
  { id: 'extra-26', title: 'Meeting Follow-up Email', defaultPrompt: 'Write follow up email after meeting:' },
  { id: 'extra-27', title: 'One-sentence Summary', defaultPrompt: 'Summarize the concept in one sentence:' },
  { id: 'extra-28', title: 'Competitive SWOT', defaultPrompt: 'Produce SWOT for company:' },
  { id: 'extra-29', title: 'Feature Spec Draft', defaultPrompt: 'Draft a feature spec for:' },
  { id: 'extra-30', title: 'Rapid Prototype Steps', defaultPrompt: 'Steps to create a rapid prototype for:' },
  { id: 'extra-31', title: 'Investor FAQ', defaultPrompt: 'Create investor FAQ for startup:' },
  { id: 'extra-32', title: 'Customer Journey Map', defaultPrompt: 'Map customer journey for:' },
  { id: 'extra-33', title: 'Persona Interview Questions', defaultPrompt: 'Write interview questions to discover needs of:' },
  { id: 'extra-34', title: 'Tone Conversion', defaultPrompt: 'Convert this message to an empathetic tone:' },
  { id: 'extra-35', title: 'Microlearning Module', defaultPrompt: 'Create a 5-minute microlearning on:' },
  { id: 'extra-36', title: 'Deal-closing script', defaultPrompt: 'Script to close a deal for client:' },
  { id: 'extra-37', title: 'Privacy Notice Draft', defaultPrompt: 'Draft a short privacy notice for:' },
  { id: 'extra-38', title: 'SOP Creator', defaultPrompt: 'Create a standard operating procedure for:' },
  { id: 'extra-39', title: 'Accessibility Checklist', defaultPrompt: 'Accessibility checklist for this page:' },
  { id: 'extra-40', title: 'Technical Debt Log', defaultPrompt: 'List technical-debt items for:' },
  { id: 'extra-41', title: 'Release Tweet', defaultPrompt: 'Write a tweet announcing release:' },
  { id: 'extra-42', title: 'Quick UX Flows', defaultPrompt: 'Sketch UX flow steps for:' },
  { id: 'extra-43', title: 'Onboarding Emails', defaultPrompt: 'Write a 3-part onboarding email sequence for new users of:' },
  { id: 'extra-44', title: 'Refund Policy Draft', defaultPrompt: 'Draft a fair refund policy for:' },
  { id: 'extra-45', title: 'Annual Report Summary', defaultPrompt: 'Summarize annual report highlights:' },
  { id: 'extra-46', title: 'Partner Outreach Email', defaultPrompt: 'Write outreach email to potential partner:' },
  { id: 'extra-47', title: 'Localization Glossary', defaultPrompt: 'Create glossary for localization of terms for:' },
  { id: 'extra-48', title: 'Content Repurposing Plan', defaultPrompt: 'Repurpose this blog into social posts and email:' },
  { id: 'extra-49', title: 'KPI Dashboard Outline', defaultPrompt: 'Outline KPIs to track for:' },
  { id: 'extra-50', title: 'Press Kit Items', defaultPrompt: 'List assets for a press kit:' },
  { id: 'extra-51', title: 'Sales Objection Responses', defaultPrompt: 'Respond to objection: “We don’t have budget”' },
  { id: 'extra-52', title: 'Localization Test Cases', defaultPrompt: 'List test cases for localized UI:' },
  { id: 'extra-53', title: 'API Contract Summary', defaultPrompt: 'Summarize the API contract for endpoint:' },
  { id: 'extra-54', title: 'Partnership Terms', defaultPrompt: 'Draft simple partnership terms for collaboration:' },
  { id: 'extra-55', title: 'Influencer Outreach', defaultPrompt: 'Write an outreach message to an influencer about:' },
  { id: 'extra-56', title: 'Customer Success Plan', defaultPrompt: 'Create a 30/60/90 customer success plan for:' },
  { id: 'extra-57', title: 'Community Guidelines', defaultPrompt: 'Draft short community guidelines for:' },
  { id: 'extra-58', title: 'Deployment Checklist', defaultPrompt: 'Checklist to deploy a web app to production:' },
  { id: 'extra-59', title: 'Airtable Schema Suggestion', defaultPrompt: 'Suggest an Airtable schema for tracking:' },
  { id: 'extra-60', title: 'Micro-SaaS Idea', defaultPrompt: 'Pitch a micro-SaaS idea that solves:' }
];

export default features;
