// Minimal metadata for 80 features (frontend uses /api/features and triggers)
const features = [
  { id: 'chat', defaultPrompt: 'Hello, tell me about yourself.' },
  { id: 'summarize', defaultPrompt: 'Summarize this text:' },
  { id: 'translate', defaultPrompt: 'Translate the following to English:' },
  { id: 'paraphrase', defaultPrompt: 'Paraphrase this sentence:' },
  { id: 'grammar', defaultPrompt: 'Correct grammar for:' },
  { id: 'rewrite-tone', defaultPrompt: 'Rewrite this to sound more formal:' },
  { id: 'qa', defaultPrompt: 'Answer the question:' },
  { id: 'codegen', defaultPrompt: 'Write code to:' },
  { id: 'explain-code', defaultPrompt: 'Explain this code:' },
  { id: 'fix-bug', defaultPrompt: 'Find bugs and suggest fixes for the code:' },
  { id: 'unit-tests', defaultPrompt: 'Generate unit tests for this function:' },
  { id: 'sql-gen', defaultPrompt: 'Produce an SQL query to:' },
  { id: 'data-clean', defaultPrompt: 'How to clean dataset with columns: ...' },
  { id: 'excel-formula', defaultPrompt: 'Create an Excel formula to:' },
  { id: 'image-gen', defaultPrompt: 'Create a prompt to generate an image of:' },
  { id: 'image-edit', defaultPrompt: 'How to edit an image to:' },
  { id: 'text-to-speech', defaultPrompt: 'Convert this text to SSML:' },
  { id: 'speech-to-text', defaultPrompt: 'Transcribe the following audio (describe audio content):' },
  { id: 'summarize-audio', defaultPrompt: 'Summarize the transcript:' },
  { id: 'meeting-notes', defaultPrompt: 'Create meeting notes from the following:' },
  { id: 'conversation-insights', defaultPrompt: 'Extract insights from the conversation:' },
  { id: 'sentiment', defaultPrompt: 'Analyze sentiment for:' },
  { id: 'entity-extraction', defaultPrompt: 'Extract entities from:' },
  { id: 'keyword-extract', defaultPrompt: 'Extract keywords from:' },
  { id: 'email-draft', defaultPrompt: 'Write an email to a hiring manager applying for:' },
  { id: 'cover-letter', defaultPrompt: 'Write a cover letter for the role:' },
  { id: 'resume-review', defaultPrompt: 'Review this resume and give suggestions:' },
  { id: 'job-descriptions', defaultPrompt: 'Create a job description for a:' },
  { id: 'idea-brainstorm', defaultPrompt: 'Brainstorm ideas for:' },
  { id: 'marketing-copy', defaultPrompt: 'Write short ad copy for:' },
  { id: 'seo-optimizer', defaultPrompt: 'Optimize this content for SEO:' },
  { id: 'product-namer', defaultPrompt: 'Generate product names for:' },
  { id: 'ux-review', defaultPrompt: 'Review this UI/UX and suggest improvements:' },
  { id: 'a-b-test', defaultPrompt: 'Suggest A/B test ideas for:' },
  { id: 'legal-summarize', defaultPrompt: 'Summarize this legal document:' },
  { id: 'privacy-review', defaultPrompt: 'Suggest privacy best practices for an app that:' },
  { id: 'cyber-ops', defaultPrompt: 'Security checklist for a web app:' },
  { id: 'design-system', defaultPrompt: 'Create a basic design token set for a product:' },
  { id: 'tone-analyzer', defaultPrompt: 'Analyze tone for the text:' },
  { id: 'persona-gen', defaultPrompt: 'Create a user persona for a product used by:' },
  { id: 'roadmap-gen', defaultPrompt: 'Generate a 6-month roadmap for:' },
  { id: 'feature-prioritize', defaultPrompt: 'Prioritize these features using RICE:' },
  { id: 'bug-report', defaultPrompt: 'Create a bug report for the issue:' },
  { id: 'changelog', defaultPrompt: 'Write release notes for these changes:' },
  { id: 'scheduler', defaultPrompt: 'Suggest meeting times for participants in:' },
  { id: 'summary-action', defaultPrompt: 'Extract action items from the meeting transcript:' },
  { id: 'visualize-data', defaultPrompt: 'Suggest visualizations for dataset with columns:' },
  { id: 'regex-gen', defaultPrompt: 'Create a regex to match:' },
  { id: 'explain-ml', defaultPrompt: 'Explain the concept of:' },
  { id: 'prompt-engineer', defaultPrompt: 'Improve this prompt:' },
  { id: 'persona-chat', defaultPrompt: 'Act as a friendly travel agent who:' },
  { id: 'story-gen', defaultPrompt: 'Write a short story about:' },
  { id: 'poetry', defaultPrompt: 'Write a short poem about:' },
  { id: 'lesson-plan', defaultPrompt: 'Create a lesson plan for teaching:' },
  { id: 'flashcards', defaultPrompt: 'Create flashcards for the topic:' },
  { id: 'math-solver', defaultPrompt: 'Solve this math problem step-by-step:' },
  { id: 'chem-helper', defaultPrompt: 'Explain the reaction:' },
  { id: 'medical-info', defaultPrompt: 'Explain symptoms and possible causes for:' },
  { id: 'fitness-plan', defaultPrompt: 'Create a 4-week fitness plan for someone who:' },
  { id: 'meal-plan', defaultPrompt: 'Create a 7-day meal plan for:' },
  { id: 'budgeting', defaultPrompt: 'Create a monthly budget for income and expenses:' },
  { id: 'tax-tips', defaultPrompt: 'General tax tips for a freelancer in:' },
  { id: 'trivia', defaultPrompt: 'Create 5 trivia questions about world capitals' },
  { id: 'quiz-maker', defaultPrompt: 'Create a 10-question multiple-choice quiz on:' },
  { id: 'game-idea', defaultPrompt: 'Suggest indie game concepts for mobile devices:' },
  { id: 'music-lyrics', defaultPrompt: 'Write a chorus for a pop song about:' },
  { id: 'chord-prog', defaultPrompt: 'Suggest a chord progression for a melancholic song in C major' },
  { id: 'photo-caption', defaultPrompt: 'Write a caption for a photo of:' },
  { id: 'resume-tailor', defaultPrompt: 'Tailor this resume for the job posting:' },
  { id: 'interview-prep', defaultPrompt: 'Generate common interview questions for a software engineer role' },
  { id: 'cold-email', defaultPrompt: 'Write a cold email to a potential client about:' },
  { id: 'sales-pitch', defaultPrompt: 'Create a short sales pitch for:' },
  { id: 'invest-summary', defaultPrompt: 'Summarize this investment memo into key points:' },
  { id: 'risk-assess', defaultPrompt: 'Assess risks for the project:' },
  { id: 'compliance-check', defaultPrompt: 'Compliance checklist for a SaaS handling user data:' },
  { id: 'translation-multiple', defaultPrompt: 'Translate this into Spanish, French, and German:' },
  { id: 'voice-persona', defaultPrompt: 'Create a voice persona for a calm, trustworthy narrator' }
];

export default features;
